### ISSUE TITLE
StyleCop inserts file headers and member docs on operations like "remove unused usings"

### ISSUE THREAD

**Issue by ChrSteinert** [kubiix/ReSharper.StyleCop#3] opened 2015-02-11 09:29 UTC
Having R# 9 and the StyleCop extension installed, operations like removing unused usings in a file seems to execute the silent cleanup which, unconfigurably, inserts file header and documents all class members.

**Comment by NikolayIT** [comment] 2015-02-11 15:45
I am having the same issue here.

**Comment by RalfKoban** [comment] 2015-02-17 09:39
I'm having the same issue here. The cause of the problem seems that the Code Style page shows an "Update File Header Style" entry for StyleCop which is set to "Insert header if it's missing".
Unfortunately, there seems to be no Option for the moment to completely deactivate that Header (e.g. by an option "Do not change").

**Comment by MoonStorm** [comment] 2015-02-23 16:54
Same problem. Changing that setting to "Completely replace header" but having no text in the header section does nothing. The copyright section still shows and to be honest I don't know where it's coming from. Checked and re-checked all the settings, including the "File Headers" section in StyleCop, which  is all turned off.

**Comment by PavelA85** [comment] 2015-03-03 19:52
Yeah, same issue here with R# 9.0 Update 1 and ReSharper.StyleCop 4.7.50-beta3 extension
I tried to update SA1633SA1641UpdateFileHeader option in GlobalSettingsStorage.DotSettings and solution.sln.DotSettings.user with Ignore value, but still no luck - I'm getting header on every file, that gets "mass" update from R#, e.g. Remove "this" in the file/folder/solution

**Comment by mreu** [comment] 2015-04-17 17:51
I have the same problem and this is really annoying. Removed the Resharper StyleCop extension for now. Hope that there will be a solution soon. I love to work with StyleCop inside Resharper.

**Comment by RichardReeves** [comment] 2015-04-24 09:53
We are suffering from this too. Delighted to find ReSharper.StyleCop; but this is really annoying for us. We don't use file headers at all, so this causes us extra work to manually remove the header. I also don't see why you would want to add/replace a header when the action I'm asking it to do is "Remove unused usings" - these are not related actions. Please add an option to switch this off.

**Comment by Neil-T** [comment] 2015-05-27 09:31
Another problem with this feature is that if a file header contains a '<summary>' element then it gets removed (presumably because the plug-in checks whether the summary immediately precedes e.g. a class or class member declaration, which it does not in this case). This is obviously undesirable and very frustrating - it essentially means we cannot use the 'Remove unused usings' feature. Please fix this!

**Comment by rhysawilliams2010** [comment] 2015-06-15 22:14
This is an issue me and my colleagues too. It would be great if this could be resolved.

**Comment by jamsoft** [comment] 2015-07-07 06:48
This is driving me nuts as well.  5 months and still noone even assigned to the issue.

**Comment by jstadnicki** [comment] 2015-07-07 06:50
Last hope is:
"source code will be available later"

**Comment by jamsoft** [comment] 2015-07-07 09:33
What the message from 6 months ago?

**Comment by dfyx** [comment] 2015-07-07 10:11
I sent an email to @kubiix today. If I don't get an answer within the next few days, I guess we can assume the project is dead.

**Comment by MoonStorm** [comment] 2015-07-07 15:56
I think we're barking at the wrong tree here. According to [this](https://stylecopforresharper.codeplex.com/)

`StyleCop for ReSharper has now merged with StyleCop - we're in the process of migrating content over to the new StyleCop site - please download / report bugs / ask questions there: See http://stylecop.codeplex.com`

**Comment by ianlevesque** [comment] 2015-07-07 16:04
@MoonStorm that's extremely old information. The codeplex site hasn't seen any code since it was abandoned last march http://stylecop.codeplex.com/SourceControl/list/changesets

We're all using this fork for that reason, we really just need the code to continue this.  In the meantime I've personally switched to https://github.com/DotNetAnalyzers/StyleCopAnalyzers/ which, while imperfect, is at least open source and actively developed.

**Comment by jamsoft** [comment] 2015-07-07 16:40
I'm thinking of uninstalling this for now to be honest.

**Comment by dfyx** [comment] 2015-07-14 08:31
> I sent an email to @kubiix today. If I don't get an answer within the next few days, I guess we can assume the project is dead.

Aaaand it's dead...

**Comment by meh-uk** [comment] 2015-07-22 09:33
I've spoken to JetBrains support to see if we can get the source code or something.

**Comment by mariomeyrelles** [comment] 2015-07-26 01:05
What would we need to study in order to be able to help?

**Closed as completed** 2015-09-10 13:28 UTC

**Comment by MoonStorm** [comment] 2015-09-10 17:17
@ChrSteinert and you closed it because...

**Comment by ChrSteinert** [comment] 2015-09-10 17:19
This repo is considered dead and moved on to https://github.com/StyleCop/StyleCop .
There should soon be an correct R# 9.2 release :)
